### PR TITLE
Add Baidu map support

### PR DESCRIPTION
**Pull request by X-Mars**
We can use Baidu map now.
The ak for test is **wINcgFmL1HyM7gWoQ5uPu6Xt9szz3chV** , I will delete it after merged.
The options for test is 
```js
option = {
        tooltip: {
          trigger: "item",
        },
        bmap: {
          // 地图展示的中心，即加载时首先出现在人眼前的点
          center: [104.114129, 37.550339], 
          // 当前地图缩放的大小，如果是一个省内的一些地方，那么zoom值应该设置得大点
          // 设置的初始值大小应根据要展示的数据而定
          zoom: 5, 
          roam: true, //允许缩放
          // 个性化地图
          mapStyleV2: {},
        },
      };
return option;
```

### CODE REVIEW

**Comment by X-Mars** [comment]
WX20221029-183253

**Comment by mikhail-vl** [comment]
@X-Mars Thank you, I will review it tomorrow and will include in the upcoming version.

**Review by mikhail-vl — APPROVED** [review]
Looks good!

**Comment by mikhail-vl** [comment]
@X-Mars Thank you for contributing. I did see updates and merged into `main`.

  I am finishing tutorial how to use Baidu maps and will release a new version later today.

**Comment by X-Mars** [comment]
@mikhail-vl This‘s good news, waiting for the new version. 👍🏻

**Comment by mikhail-vl** [comment]
@X-Mars, it's ready https://github.com/VolkovLabs/volkovlabs-echarts-panel/releases/tag/v3.6.0.

  Let us know if there is anything else.

**Comment by X-Mars** [comment]
@mikhail-vl  Cannot find the latest version on the [grafana.com](https://grafana.com/grafana/plugins/volkovlabs-echarts-panel/?tab=changelog)

**Comment by mikhail-vl** [comment]
@X-Mars It's still under review, there is no timeline when Grafana team approve it.

  Meanwhile, you can download it directly from the GitHub and install using `grafana-cli` or replacing plugin in the `plugins` folder.

**Comment by X-Mars** [comment]
@mikhail-vl ok, thanks

**Pull request merged**
